version: '3.2'

services:

  teamcity:
    image: jetbrains/teamcity-server:2018.1.5-linux
    ports: 
      - "8111:8111"
    networks:
      - teamcity
    volumes:
      - type: bind
        source: ./teamcity/teamcity/data
        target: /data/teamcity_server/datadir
      - ./teamcity/teamcity/logs:/opt/teamcity/logs:rw

  teamcity-agent:
    image: jetbrains/teamcity-agent:2018.1.5-linux
    environment:
      SERVER_URL: "teamcity:8111"
      DOCKER_IN_DOCKER: "start"
    networks:
      - teamcity
    volumes:
      - ./teamcity/teamcity-agent/conf:/data/teamcity_agent/conf:rw
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/buildagent/work:/opt/buildagent/work 
      - /opt/buildagent/temp:/opt/buildagent/temp 
      - /opt/buildagent/tools:/opt/buildagent/tools 
      - /opt/buildagent/plugins:/opt/buildagent/plugins 
      - /opt/buildagent/system:/opt/buildagent/system

networks:
  teamcity:
    driver: bridge
