version: '2'

services:

  client:
    build:
      context: client-main/
    ports: 
      - "80:80"
    networks:
      - sharifyr
    volumes:
      - ./client-main:/usr/src/app:rw

  server:
    build:
      context: server-social/
    ports: 
      - "3000:3000"
    depends_on:
      - db
    networks:
      - sharifyr
      - elk
    volumes:
      - ./server-social:/usr/src/app:rw

  db:
    image: postgres
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_USER: sharifyr
      POSTGRES_PASSWORD: sharifyrpassword
    networks:
      - sharifyr

networks:

  elk:
    external:
      name: dockerelk_elk
  sharifyr:
    driver: bridge